src/Entity/Produits.php
<?php

namespace App\Entity;

use App\Repository\ProduitsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProduitsRepository::class)]
class Produits
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 60)]
    private ?string $nom = null;

    #[ORM\Column(length: 20)]
    private ?string $marque = null;

    #[ORM\Column]
    private ?float $prix = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\ManyToMany(targetEntity: User::class, mappedBy: 'Favoris')]
    private Collection $users;

    #[ORM\Column(length: 200)]
    private ?string $image = null;

    #[ORM\OneToMany(mappedBy: 'produits', targetEntity: Ajouter::class)]
    private Collection $ajouters;

    #[ORM\Column(length: 255)]
    private ?string $categorie = null;

    #[ORM\Column(length: 255)]
    private ?string $scategorie = null;

    public function __construct()
    {
        $this->users = new ArrayCollection();
        $this->ajouters = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getMarque(): ?string
    {
        return $this->marque;
    }

    public function setMarque(string $marque): self
    {
        $this->marque = $marque;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }
    

    /**
     * @return Collection<int, User>
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users->add($user);
            $user->addFavori($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->removeElement($user)) {
            $user->removeFavori($this);
        }

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    /**
     * @return Collection<int, Ajouter>
     */
    public function getAjouters(): Collection
    {
        return $this->ajouters;
    }

    public function addAjouter(Ajouter $ajouter): self
    {
        if (!$this->ajouters->contains($ajouter)) {
            $this->ajouters->add($ajouter);
            $ajouter->setProduits($this);
        }

        return $this;
    }

    public function removeAjouter(Ajouter $ajouter): self
    {
        if ($this->ajouters->removeElement($ajouter)) {
            // set the owning side to null (unless already changed)
            if ($ajouter->getProduits() === $this) {
                $ajouter->setProduits(null);
            }
        }

        return $this;
    }

    public function getCategorie(): ?string
    {
        return $this->categorie;
    }

    public function setCategorie(string $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }

    public function getScategorie(): ?string
    {
        return $this->scategorie;
    }

    public function setScategorie(string $scategorie): self
    {
        $this->scategorie = $scategorie;

        return $this;
    }
    
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(type: 'boolean')]
    private $isVerified = false;

    #[ORM\ManyToMany(targetEntity: Produits::class, inversedBy: 'users')]
    private Collection $Favoris;

    #[ORM\OneToOne(mappedBy: 'user', cascade: ['persist', 'remove'])]
    private ?Panier $panier = null;

    public function __construct()
    {
        $this->Favoris = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    /**
     * @return Collection<int, Produits>
     */
    public function getFavoris(): Collection
    {
        return $this->Favoris;
    }

    public function addFavori(Produits $favori): self
    {
        if (!$this->Favoris->contains($favori)) {
            $this->Favoris->add($favori);
        }

        return $this;
    }

    public function removeFavori(Produits $favori): self
    {
        $this->Favoris->removeElement($favori);

        return $this;
    }

    public function getPanier(): ?Panier
    {
        return $this->panier;
    }

    public function setPanier(?Panier $panier): self
    {
        // unset the owning side of the relation if necessary
        if ($panier === null && $this->panier !== null) {
            $this->panier->setUser(null);
        }

        // set the owning side of the relation if necessary
        if ($panier !== null && $panier->getUser() !== $this) {
            $panier->setUser($this);
        }

        $this->panier = $panier;

        return $this;
    }
}

src/Form/ProduitsType.php
<?php

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Validator\Constraints\File;

class ProduitsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
        ->add('image', FileType::class, ['attr' => ['class'=> 'form-control'], 'label_attr' => ['class'=> 'fw-bold'],
            'label' => 'Image',
            'mapped' => false,
            'required' => false,
            'data_class' => null,
            'constraints' => [
                new File([
                    'mimeTypes' => [
                        'image/webp',
                        'image/jpeg',
                        'image/png',
                    ],
                    'mimeTypesMessage' => 'Le site accepte uniquement les fichiers WEBP, PNG et JPG',
                    ])
                ],
        ])
        ->add('nom', TextType::class, ['attr' => ['class'=> 'form-control'], 'label_attr' => ['class'=> 'fw-bold']])
        ->add('marque',TextType::class, ['attr' => ['class'=> 'form-control'], 'label_attr' => ['class'=> 'fw-bold']])
        ->add('prix', NumberType::class, ['attr' => ['class'=> 'form-control'], 'label_attr' => ['class'=> 'fw-bold']])
        ->add('description', TextareaType::class, ['attr' => ['class'=> 'form-control', 'rows'=>'7', 'cols' => '7'], 'label_attr' => ['class'=> 'fw-bold']])
        ->add('categorie', ChoiceType::class, [
            'attr' => ['class'=> 'form-control'], 'label_attr' => ['class'=> 'fw-bold'],
            'choices'  => [
                'Extérieur' => 'Extérieur',
                'Intérieur' => 'Intérieur',
                'Décoration' => 'Décoration',
            ],
        ])
        ->add('scategorie', ChoiceType::class, [ //scatégorie n'est pas forcéme,nt lié à catégorie mais je ne peux tranféré ceci en tant que entité en raison du manque de temp,je le ferai ensuite lors d'une mise à jour
            'attr' => ['class'=> 'form-control'], 'label_attr' => ['class'=> 'fw-bold'],
            'choices'  => [
                'Filaire' => 'Filaire',
                'Piscines Spas' => 'Piscines Spas',
                'Laveur' => 'Laveur',
                'Bureau' => 'Bureau',
            ],
        ])
        ->add('envoyer', SubmitType::class, ['attr' => ['class'=> 'btn bg-primary text-white m-4' ], 'row_attr' => ['class' => 'text-center'],])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            // Configure your form options here
        ]);
    }
}

src/Controller/ProduitsController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Produits;
use App\Form\ProduitsType;
use App\Form\ModifProduitsType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\String\Slugger\SluggerInterface;

class ProduitsController extends AbstractController
{
    #[Route('/produits', name: 'produits')]
    public function produits(): Response
    {
        $form = $this->createForm(ProduitsType::class);
        return $this->render('produits/index.html.twig', [
            'form' => $form->createView()
        ]);
    }
    #[Route('/liste-produits', name: 'liste-produits')]
    public function listeProduits(EntityManagerInterface $entityManagerInterface): Response
    {
        $repoProduits = $entityManagerInterface->getRepository(Produits::class);
        $produits = $repoProduits->findAll();
        return $this->render('produits/liste-produits.html.twig', [
           'produits' => $produits
        ]);
    } 
    //route pour afficher les contacts un par un
    #[Route('/modif-produits/{id}', name: 'modif-produits')]
    public function ModifProduitsController(EntityManagerInterface $entityManagerInterface,Request $request, SluggerInterface $slugger): Response
    {
        $id=$request->get('id');
        $repoProduits = $entityManagerInterface->getRepository(Produits::class);
        $produits = $repoProduits->find($id);
        $form=$this->createForm(ModifProduitsType::class,$produits);

        if($request->isMethod('POST')){
            $form->handleRequest($request);
            if ($form->isSubmitted()&&$form->isValid()){
                $image = $form->get('image')->getData();
                if($image){
                    $nomFichier = pathinfo($image->getClientOriginalName(), PATHINFO_FILENAME);
                    $nomFichier = $slugger->slug($nomFichier);
                    $nomFichier = $nomFichier.'-'.uniqid().'.'.$image->guessExtension();
                    try{
                        $image->move($this->getParameter('file_directory'), $nomFichier);
                        $this->addFlash('notice', 'Image envoyée');
                        $produits->setImage($nomFichier);
                    }
                    catch(FileException $e){
                        $this->addFlash('notice', 'Erreur d\'envoi');
                    }
                }
              
                $entityManagerInterface->persist($produits);
                $entityManagerInterface->flush();

                $this->addFlash('notice','Modification réussi');
                return $this->redirectToRoute('liste-produits');
              
            }
        }


        return $this->render('produits/modif-produits.html.twig', [
           'modif' => $produits,
           'form' => $form->createView()
        ]);
    }

    #[Route('/supp-produits/{id}', name: 'supp-produits')]
    public function suppProduits(EntityManagerInterface $entityManagerInterface,Request $request): Response
    {
        $id=$request->get('id');
        $repoProduits = $entityManagerInterface->getRepository(Produits::class);
        $produits = $repoProduits->find($id);
              
                $entityManagerInterface->remove($produits);
                $entityManagerInterface->flush();

                $this->addFlash('notice','Suppression Terminé');
                return $this->redirectToRoute('liste-produits');

        return $this->render('produits/supp-produits.html.twig', [
           'modif' => $produits,
           'form' => $form->createView()
        ]);
    }

    #[Route('/ajout-produits', name: 'ajout-produits')]
    public function AjoutProduits(EntityManagerInterface $entityManagerInterface,Request $request, SluggerInterface $slugger): Response
    {
        $produits = new Produits();
        $form = $this->createForm(ProduitsType::class, $produits);

        if($request->isMethod('POST')){
            $form->handleRequest($request);
            if ($form->isSubmitted()&&$form->isValid()){
                $image = $form->get('image')->getData();
                if($image){
                    $nomFichier = pathinfo($image->getClientOriginalName(), PATHINFO_FILENAME);
                    $nomFichier = $slugger->slug($nomFichier);
                    $nomFichier = $nomFichier.'-'.uniqid().'.'.$image->guessExtension();
                    try{
                        $image->move($this->getParameter('file_directory'), $nomFichier);
                        $this->addFlash('notice', 'Image envoyée');
                        $produits->setImage($nomFichier);
                    }
                    catch(FileException $e){
                        $this->addFlash('notice', 'Erreur d\'envoi');
                    }
                }
              
                $entityManagerInterface->persist($produits);
                $entityManagerInterface->flush();

                $this->addFlash('notice','Modification réussi');
                return $this->redirectToRoute('liste-produits');
              
            }
        }

        return $this->render('produits/ajout-produits.html.twig', [
           'form' => $form->createView()
        ]);
    }
    #[Route('produits/infoproduit{id}', name: 'infoproduit')]
    public function infoproduit(Request $request,int $id): Response
    {
        $entityManager= $this->getDoctrine()->getManager();
        $product = $entityManager->getRepository(Produits::class)->find($id);;
        return $this->render('produits/infoproduit.html.twig', [
            'produits'=>$product
        ]);
    }
}

templates/produits/ajout-produits.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	{{parent()}}Affichage des catégories
{% endblock %}

{% block body %}
	<div class='col-10 '>
		<a href="{{path('liste-produits')}}">
			<button class="btn ">
				<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-backspace-fill " viewbox="0 0 16 16">
					<path d="M15.683 3a2 2 0 0 0-2-2h-7.08a2 2 0 0 0-1.519.698L.241 7.35a1 1 0 0 0 0 1.302l4.843 5.65A2 2 0 0 0 6.603 15h7.08a2 2 0 0 0 2-2V3zM5.829 5.854a.5.5 0 1 1 .707-.708l2.147 2.147 2.146-2.147a.5.5 0 1 1 .707.708L9.39 8l2.146 2.146a.5.5 0 0 1-.707.708L8.683 8.707l-2.147 2.147a.5.5 0 0 1-.707-.708L7.976 8 5.829 5.854z"/>
				</svg>
			</button>
		</a>
	</div>

	{{form(form)}}{% endblock %}

templates/produits/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{parent()}}Produits{% endblock %}

{% block body %}
    <div class="container-fluid">
	    <div class="row justify-content-center">
			
                    <div class="col-10 text-primary">
                        <h1 class="text-center text-primary mt-4 pt-4 display-1 fw-bold">Produits</h1>
                        {{form(form)}}
                    </div>    
	    </div>
	</div>
    
{% endblock %}

templates/produits/infoproduit.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	{{parent()}}Article
{% endblock %}

{% block body %}
	<div class='col-10 '>
		<a href="{{path('index')}}">
			<button class="btn ">
				<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-backspace-fill " viewbox="0 0 16 16">
					<path d="M15.683 3a2 2 0 0 0-2-2h-7.08a2 2 0 0 0-1.519.698L.241 7.35a1 1 0 0 0 0 1.302l4.843 5.65A2 2 0 0 0 6.603 15h7.08a2 2 0 0 0 2-2V3zM5.829 5.854a.5.5 0 1 1 .707-.708l2.147 2.147 2.146-2.147a.5.5 0 1 1 .707.708L9.39 8l2.146 2.146a.5.5 0 0 1-.707.708L8.683 8.707l-2.147 2.147a.5.5 0 0 1-.707-.708L7.976 8 5.829 5.854z"/>
				</svg>
			</button>
		</a>
	</div>

	<div class="container">
		<div class="row g-3">
			<div class='col-6'>
				<img src="{{asset('img/'~produits.image)}}" class="w-100 d-block">
			</div>
			<div class="col-6 mt-auto mb-auto">
				<div class=" text-center h3 ">
					{{produits.nom}}
				</div><br>
				<div class=" text-center h5 ">
					{{produits.description}}
				</div><br>
				<div class=" text-center h5 p-1 ">
					{{produits.prix}}
					€
				</div><br>

				<!--Button trigger modal-->
				<div class="text-center row ">
					<div class='col-2'>

						{% if is_granted('IS_AUTHENTICATED_FULLY') %}

							{% if produits in app.user.favoris %}
								<div class="mb-2">
									<a href="{{path('favoris',{'id':produits.id,'action':'supprimer'})}}">
										<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-suit-heart-fill" viewbox="0 0 16 16">
											<path d="M4 1c2.21 0 4 1.755 4 3.92C8 2.755 9.79 1 12 1s4 1.755 4 3.92c0 3.263-3.234 4.414-7.608 9.608a.513.513 0 0 1-.784 0C3.234 9.334 0 8.183 0 4.92 0 2.755 1.79 1 4 1z"/>
										</svg>
									</a>
								</div>
							{% else %}
								<div class="mb-2">
									<a href="{{path('favoris',{'id':produits.id,'action':'ajouter'})}}">
										<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-suit-heart" viewbox="0 0 16 16">
											<path d="m8 6.236-.894-1.789c-.222-.443-.607-1.08-1.152-1.595C5.418 2.345 4.776 2 4 2 2.324 2 1 3.326 1 4.92c0 1.211.554 2.066 1.868 3.37.337.334.721.695 1.146 1.093C5.122 10.423 6.5 11.717 8 13.447c1.5-1.73 2.878-3.024 3.986-4.064.425-.398.81-.76 1.146-1.093C14.446 6.986 15 6.131 15 4.92 15 3.326 13.676 2 12 2c-.777 0-1.418.345-1.954.852-.545.515-.93 1.152-1.152 1.595L8 6.236zm.392 8.292a.513.513 0 0 1-.784 0c-1.601-1.902-3.05-3.262-4.243-4.381C1.3 8.208 0 6.989 0 4.92 0 2.755 1.79 1 4 1c1.6 0 2.719 1.05 3.404 2.008.26.365.458.716.596.992a7.55 7.55 0 0 1 .596-.992C9.281 2.049 10.4 1 12 1c2.21 0 4 1.755 4 3.92 0 2.069-1.3 3.288-3.365 5.227-1.193 1.12-2.642 2.48-4.243 4.38z"/>
										</svg>
									</a>
								</div>
							{% endif %}

							{% if produits in app.user.panier %}
								<div class="mb-2">
									<a href="{{path('panier',{'id':produits.id,'action':'supprimer'})}}">
										<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart-check-fill" viewbox="0 0 16 16">
											<path d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1H.5zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm-1.646-7.646-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 1 1 .708-.708L8 8.293l2.646-2.647a.5.5 0 0 1 .708.708z"/>
										</svg>
									</a>
								</div>
							{% else %}
								<div class="mb-2">
									<a href="{{path('ajout-panier', {'id':produits.id,'page':'index'})}}">
										<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart" viewbox="0 0 16 16">
											<path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
										</svg>
									</a>
								</div>
							{% endif %}
						{% else %}
							<div class="mb-2">
								<a href="{{path('app_login')}}">
									<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-suit-heart" viewbox="0 0 16 16">
										<path d="m8 6.236-.894-1.789c-.222-.443-.607-1.08-1.152-1.595C5.418 2.345 4.776 2 4 2 2.324 2 1 3.326 1 4.92c0 1.211.554 2.066 1.868 3.37.337.334.721.695 1.146 1.093C5.122 10.423 6.5 11.717 8 13.447c1.5-1.73 2.878-3.024 3.986-4.064.425-.398.81-.76 1.146-1.093C14.446 6.986 15 6.131 15 4.92 15 3.326 13.676 2 12 2c-.777 0-1.418.345-1.954.852-.545.515-.93 1.152-1.152 1.595L8 6.236zm.392 8.292a.513.513 0 0 1-.784 0c-1.601-1.902-3.05-3.262-4.243-4.381C1.3 8.208 0 6.989 0 4.92 0 2.755 1.79 1 4 1c1.6 0 2.719 1.05 3.404 2.008.26.365.458.716.596.992a7.55 7.55 0 0 1 .596-.992C9.281 2.049 10.4 1 12 1c2.21 0 4 1.755 4 3.92 0 2.069-1.3 3.288-3.365 5.227-1.193 1.12-2.642 2.48-4.243 4.38z"/>
									</svg>
								</a>
							</div>

							<div class="mb-2">
								<a href="{{path('app_login')}}">
									<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart" viewbox="0 0 16 16">
										<path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
									</svg>
								</a>
							</div>

						{% endif %}
					</div>
					<div class='col-10'>

						<a href="{{path('acheter',{'id':produits.id})}}">
							<button class="btn btn-primary m-auto col-7 mt-0 mb-2 mx-0">
								Acheter
							</button>
						</a>
					</div>
				</div>

				<div>


				{% endblock %}

templates/produits/modif-produits.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	{{parent()}}Affichage des catégories
{% endblock %}

{% block body %}
    {{form(form)}}
{% endblock %}

templates/produits/supp-produits.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	{{parent()}}Affichage des catégories
{% endblock %}

{% block body %}
    {{form(form)}}
{% endblock %}